//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaSoft.MvvmLight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalaSoft.MvvmLight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interface cannot be registered alone..
        /// </summary>
        internal static string AnInterfaceCannotBeRegisteredAlone {
            get {
                return ResourceManager.GetString("AnInterfaceCannotBeRegisteredAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build instance: Multiple constructors found but none marked with PreferredConstructor..
        /// </summary>
        internal static string CannotBuildInstance {
            get {
                return ResourceManager.GetString("CannotBuildInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} is already registered..
        /// </summary>
        internal static string ClassIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("ClassIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} is already registered with key {1}..
        /// </summary>
        internal static string ClassIsAlreadyRegisteredWithKey {
            get {
                return ResourceManager.GetString("ClassIsAlreadyRegisteredWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a class registered for {0}..
        /// </summary>
        internal static string ThereIsAlreadyAClassRegisteredFor {
            get {
                return ResourceManager.GetString("ThereIsAlreadyAClassRegisteredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a factory registered for {0}..
        /// </summary>
        internal static string ThereIsAlreadyAFactoryRegisteredFor {
            get {
                return ResourceManager.GetString("ThereIsAlreadyAFactoryRegisteredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a factory registered for {0} with key {1}..
        /// </summary>
        internal static string ThereIsAlreadyAFactoryRegisteredForSameKey {
            get {
                return ResourceManager.GetString("ThereIsAlreadyAFactoryRegisteredForSameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found in cache: {0}..
        /// </summary>
        internal static string TypeNotFoundInCache {
            get {
                return ResourceManager.GetString("TypeNotFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found in cache without a key: {0}.
        /// </summary>
        internal static string TypeNotFoundInCacheKeyLess {
            get {
                return ResourceManager.GetString("TypeNotFoundInCacheKeyLess", resourceCulture);
            }
        }
    }
}
