#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Flowers.Resource", IsApplication=true)]

namespace Flowers
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::Flowers.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::Flowers.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int AddCommentButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int CommentText = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int CommentsList = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int DescriptionText = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int DescriptionTextView = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int FlowerImageView = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int FlowerTemplateRoot = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int FlowersList = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int LastLoadedText = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int NameText = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int NameTextView = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int RefreshButton = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int SaveCommentButton = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int Separator = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddComment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CommentsListHeaderView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Details = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FlowerTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
