//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmLightToolkit.Setup.Configure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvvmLightToolkit.Setup.Configure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of binaries (assemblies).
        /// </summary>
        public static string BinariesLocation {
            get {
                return ResourceManager.GetString("BinariesLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the link to open the folder.
        /// </summary>
        public static string BinariesLocationToolTip {
            get {
                return ResourceManager.GetString("BinariesLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend is running.
        /// </summary>
        public static string BlendIsRunningCaption {
            get {
                return ResourceManager.GetString("BlendIsRunningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend is running, user aborted configuration.
        /// </summary>
        public static string BlendIsRunningException {
            get {
                return ResourceManager.GetString("BlendIsRunningException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close Blend before you proceed. Press OK to continue installation or Cancel to... well you know..
        /// </summary>
        public static string BlendIsRunningMessage {
            get {
                return ResourceManager.GetString("BlendIsRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if a new version is available.
        /// </summary>
        public static string CheckVersionToolTip {
            get {
                return ResourceManager.GetString("CheckVersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination for Snippets.
        /// </summary>
        public static string DestinationSnippets {
            get {
                return ResourceManager.GetString("DestinationSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination for Templates.
        /// </summary>
        public static string DestinationTemplates {
            get {
                return ResourceManager.GetString("DestinationTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.galasoft.ch.
        /// </summary>
        public static string GalaSoftUrl {
            get {
                return ResourceManager.GetString("GalaSoftUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get some help.
        /// </summary>
        public static string GetHelpToolTip {
            get {
                return ResourceManager.GetString("GetHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.galasoft.ch/mvvm/getstarted.
        /// </summary>
        public static string GetHelpUrl {
            get {
                return ResourceManager.GetString("GetHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Type.
        /// </summary>
        public static string InstallationType {
            get {
                return ResourceManager.GetString("InstallationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL+WPF.
        /// </summary>
        public static string InstallBoth {
            get {
                return ResourceManager.GetString("InstallBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallContent {
            get {
                return ResourceManager.GetString("InstallContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        public static string InstallSilverlight {
            get {
                return ResourceManager.GetString("InstallSilverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the toolkit.
        /// </summary>
        public static string InstallToolTip {
            get {
                return ResourceManager.GetString("InstallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight and Windows Presentation Foundation.
        /// </summary>
        public static string InstallToolTipBoth {
            get {
                return ResourceManager.GetString("InstallToolTipBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight only.
        /// </summary>
        public static string InstallToolTipSilverlight {
            get {
                return ResourceManager.GetString("InstallToolTipSilverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Presentation Foundation only.
        /// </summary>
        public static string InstallToolTipWPF {
            get {
                return ResourceManager.GetString("InstallToolTipWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of installation (WPF, Silverlight or both).
        /// </summary>
        public static string InstallTypeToolTip {
            get {
                return ResourceManager.GetString("InstallTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF.
        /// </summary>
        public static string InstallWPF {
            get {
                return ResourceManager.GetString("InstallWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found: {0}.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the GalaSoft website.
        /// </summary>
        public static string ShowGalaSoft {
            get {
                return ResourceManager.GetString("ShowGalaSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the source code files.
        /// </summary>
        public static string ShowSourceToolTip {
            get {
                return ResourceManager.GetString("ShowSourceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder for snippets.
        /// </summary>
        public static string SnippetsFolderBrowserDialogDescription {
            get {
                return ResourceManager.GetString("SnippetsFolderBrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MVVM Light Toolkit has been configured successfully!.
        /// </summary>
        public static string SuccessInstall {
            get {
                return ResourceManager.GetString("SuccessInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder for item templates and project templates (this folder should contain the ProjectTemplates and ItemTemplates folders).
        /// </summary>
        public static string TemplatesFolderBrowserDialogDescription {
            get {
                return ResourceManager.GetString("TemplatesFolderBrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user closed the window without installing the files.
        /// </summary>
        public static string UserCancelledException {
            get {
                return ResourceManager.GetString("UserCancelledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVVM Light Toolkit V{0}.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
